Repository wecode-bootcamp-korea/33-backend-westagram-2, pull requests merged in 2022-05, with the labels that each got.

#1 [33기 박상연] Mission 1 : Django 초기세팅
  students/sangyeon/.gitignore
  students/sangyeon/manage.py
  students/sangyeon/requirements.txt
  students/sangyeon/westagram/__init__.py
  students/sangyeon/westagram/asgi.py
  students/sangyeon/westagram/settings.py
  students/sangyeon/westagram/urls.py
  students/sangyeon/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#2 [정치영] Mission 1 : Django 초기 세팅 #33
  students/chiyoung/.gitignore
  students/chiyoung/manage.py
  students/chiyoung/requirements.txt
  students/chiyoung/westagram/__init__.py
  students/chiyoung/westagram/asgi.py
  students/chiyoung/westagram/settings.py
  students/chiyoung/westagram/urls.py
  students/chiyoung/westagram/wsgi.py
Labels: 완료

#3 [33기 박상연] Mission 2: 모델링
  students/sangyeon/users/__init__.py
  students/sangyeon/users/admin.py
  students/sangyeon/users/apps.py
  students/sangyeon/users/migrations/0001_initial.py
  students/sangyeon/users/migrations/__init__.py
  students/sangyeon/users/models.py
  students/sangyeon/users/tests.py
  students/sangyeon/users/views.py
  students/sangyeon/westagram/settings.py
Labels: 멘토 리뷰 요청

#4 [임한구] Mission 1 : Django 초기세팅 #21
  students/hangu/.gitignore
  students/hangu/manage.py
  students/hangu/requirements.txt
  students/hangu/westagram/__init__.py
  students/hangu/westagram/asgi.py
  students/hangu/westagram/settings.py
  students/hangu/westagram/urls.py
  students/hangu/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#5 [정치영] Mission 2 : 모델링
  students/chiyoung/users/__init__.py
  students/chiyoung/users/admin.py
  students/chiyoung/users/apps.py
  students/chiyoung/users/migrations/0001_initial.py
  students/chiyoung/users/migrations/0002_accounts_delete_user.py
  students/chiyoung/users/migrations/__init__.py
  students/chiyoung/users/models.py
  students/chiyoung/users/tests.py
  students/chiyoung/users/views.py
  students/chiyoung/westagram/settings.py
Labels: 완료

#7 [33기 최혜인] Mission 1 : Django 초기세팅
  students/hyein/.gitignore
  students/hyein/manage.py
  students/hyein/requirements.txt
  students/hyein/westagram/__init__.py
  students/hyein/westagram/asgi.py
  students/hyein/westagram/settings.py
  students/hyein/westagram/urls.py
  students/hyein/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#6 [임한구] Mission: 모델링
  students/hangu/users/__init__.py
  students/hangu/users/admin.py
  students/hangu/users/apps.py
  students/hangu/users/migrations/0001_initial.py
  students/hangu/users/migrations/0002_alter_user_user_email_alter_user_table.py
  students/hangu/users/migrations/0003_alter_user_password_alter_user_user_email_and_more.py
  students/hangu/users/migrations/0004_user_created_at_user_updated_at.py
  students/hangu/users/migrations/__init__.py
  students/hangu/users/models.py
  students/hangu/users/tests.py
  students/hangu/users/urls.py
  students/hangu/users/views.py
  students/hangu/westagram/settings.py
Labels: 멘토 리뷰 요청

#8 [최혜인] Mission 2: 모델링
  students/hyein/users/__init__.py
  students/hyein/users/admin.py
  students/hyein/users/apps.py
  students/hyein/users/migrations/0001_initial.py
  students/hyein/users/migrations/__init__.py
  students/hyein/users/models.py
  students/hyein/users/tests.py
  students/hyein/users/views.py
  students/hyein/westagram/settings.py
Labels: 멘토 리뷰 요청

#11 [정치영] Mission 3: 회원가입 기능 구현
  students/chiyoung/users/migrations/0003_alter_accounts_email.py
  students/chiyoung/users/migrations/0004_alter_accounts_email.py
  students/chiyoung/users/models.py
  students/chiyoung/users/urls.py
  students/chiyoung/users/validators.py
  students/chiyoung/users/views.py
  students/chiyoung/westagram/urls.py
Labels: 멘토 리뷰 요청

#9 [임한구] Mission 3: 회원가입 기능 구현
  students/hangu/users/urls.py
  students/hangu/users/views.py
  students/hangu/westagram/urls.py
Labels: 멘토 리뷰 요청

#13 [33기 최혜인] 회원가입 기능 구현
  students/hyein/users/urls.py
  students/hyein/users/views.py
  students/hyein/westagram/urls.py
Labels: 멘토 리뷰 요청

#10 [33기 박상연] Mission 3: 회원가입 기능 구현
  students/sangyeon/users/urls.py
  students/sangyeon/users/views.py
  students/sangyeon/westagram/urls.py
Labels: 멘토 리뷰 요청

#12 [임한구] Mission 4: 로그인 기능 구현
  students/hangu/users/urls.py
  students/hangu/users/views.py
Labels: 완료

#16 [33기 최혜인] Mission 4: 로그인 기능 구현
  students/hyein/users/urls.py
  students/hyein/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#15 [33기 박상연] Mission 4: 로그인 기능 구현
  students/sangyeon/users/urls.py
  students/sangyeon/users/views.py
  students/sangyeon/westagram/urls.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#14 [정치영] Mission 4 : 로그인 기능 구현
  students/chiyoung/users/urls.py
  students/chiyoung/users/views.py
  students/chiyoung/westagram/settings.py
Labels: 멘토 리뷰 요청

#19 [33기 최혜인] Mission 5: 회원가입 비밀번호 암호화 적용
  students/hyein/users/migrations/0002_alter_user_password.py
  students/hyein/users/models.py
  students/hyein/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#21 [정치영] Mission 5: 회원가입 비밀번호 암호화 적용
  students/chiyoung/requirements.txt
  students/chiyoung/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#20 [33기 박상연] Mission 5: 회원가입 비밀번호 암호화 적용
  students/sangyeon/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#17 [임한구] Mission 5: 회원가입 비밀번호 암호화 적용
  students/hangu/requirements.txt
  students/hangu/users/views.py
Labels: 완료

#22 [정치영] Mission 6: 로그인 JWT 발급
  students/chiyoung/users/views.py
  students/chiyoung/westagram/settings.py
Labels: 완료

#24 [33기 박상연] Mission 6: 로그인 JWT 발급
  students/sangyeon/users/views.py
  students/sangyeon/westagram/settings.py
Labels: 멘토 리뷰 요청

#25 [33기 최혜인] Mission 6: 로그인 JWT 발급
  students/hyein/users/views.py
  students/hyein/westagram/settings.py
Labels: 멘토 리뷰 요청
